# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=128)),
                ('track_genre', models.CharField(choices=[('BL', 'Blues'), ('CL', 'Classical'), ('EL', 'Electronic'), ('HM', 'Heavy Metal'), ('HH', 'Hip Hop / R&B'), ('JA', 'Jazz'), ('PO', 'Pop'), ('RA', 'Rap'), ('RE', 'Reggae'), ('RO', 'Rock')], max_length=2)),
                ('track_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
                ('track_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
        ),
    ]
