# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_genre',
            field=models.CharField(choices=[('BL', 'Blues'), ('CL', 'Classical'), ('EL', 'Electronic'), ('HM', 'Heavy Metal'), ('HH', 'Hip Hop / R&B'), ('JA', 'Jazz'), ('LA', 'Latin'), ('PO', 'Pop'), ('RA', 'Rap'), ('RE', 'Reggae'), ('RO', 'Rock')], max_length=2),
        ),
    ]
