# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20170508_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='track_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
        ),
    ]
